name: CI Pipeline

# Kích hoạt robot khi có code push lên bất kỳ nhánh nào hoặc tạo Pull Request
on:
  push:
    branches: ["**"] 
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    # Khởi tạo Database Postgres để chạy Test
    services:
      db:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: devops_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
        # Bước 1: Tải code từ GitHub về máy ảo
        - name: Checkout code
          uses: actions/checkout@v3

        # Bước 2: Cài đặt môi trường Node.js
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18'

        # Bước 3: Tạo bảng dữ liệu (Để tránh lỗi 500 do Database trống)
        - name: Setup Database Table
          run: |
            # Chờ database sẵn sàng và tạo bảng todos
            docker run --network host postgres:15-alpine psql -h localhost -U postgres -d devops_db -c "CREATE TABLE IF NOT EXISTS todos (id SERIAL PRIMARY KEY, title TEXT NOT NULL, completed BOOLEAN DEFAULT FALSE);"
          env:
            PGPASSWORD: postgres

        # Bước 4: Cài đặt thư viện
        - name: Install dependencies
          run: npm install
          working-directory: ./backend

        # Bước 5: Chạy Test (Dùng forceExit để không bị treo robot)
        - name: Run tests
          run: npm test -- --forceExit --detectOpenHandles
          working-directory: ./backend
          env:
            DB_HOST: localhost
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_NAME: devops_db
            DB_PORT: 5432
            NODE_ENV: test